from fastapi import APIRouter, HTTPException
import mysql.connector
import pyotp
import qrcode
import io
import base64
from backend.app.database import obtener_conexion, ensure_totp_column_exists
from backend.app.models import DatosValidacionTOTP

router = APIRouter(prefix="/totp", tags=["Seguridad TOTP (2FA)"])

@router.post("/setup/{id_usuario}")
def setup_totp(id_usuario: int):
    """
    Enrolls a user into 2FA by generating a Base32 TOTP secret key, saving it to the database,
    and returning a Base64-encoded QR Code image for authenticator app enrollment.
    """
    conexion = obtener_conexion()
    if not conexion:
        raise HTTPException(status_code=500, detail="Error de conexión a la base de datos.")

    ensure_totp_column_exists(conexion)
    cursor = conexion.cursor()

    try:
        cursor.execute("SELECT correo, totp_secret FROM usuarios WHERE id_usuario = %s", (id_usuario,))
        resultado = cursor.fetchone()
        
        if not resultado:
            raise HTTPException(status_code=404, detail="Usuario no encontrado.")
            
        correo, secret_existente = resultado

        if not secret_existente:
            totp_secret = pyotp.random_base32()
            cursor.execute("UPDATE usuarios SET totp_secret = %s WHERE id_usuario = %s", (totp_secret, id_usuario))
            
            sql_log = "INSERT INTO logs_auditoria (evento, id_usuario) VALUES (%s, %s)"
            cursor.execute(sql_log, ("Enrolamiento de 2FA TOTP iniciado", id_usuario))
            conexion.commit()
        else:
            totp_secret = secret_existente

        totp = pyotp.TOTP(totp_secret)
        provisioning_uri = totp.provisioning_uri(name=correo, issuer_name="NMMVA_CORP")

        qr_img = qrcode.make(provisioning_uri)
        img_buffer = io.BytesIO()
        qr_img.save(img_buffer, format="PNG")
        qr_base64 = base64.b64encode(img_buffer.getvalue()).decode("utf-8")

        return {
            "status": "Éxito",
            "id_usuario": id_usuario,
            "totp_secret": totp_secret,
            "provisioning_uri": provisioning_uri,
            "qr_code_base64": qr_base64
        }

    except mysql.connector.Error as err:
        conexion.rollback()
        raise HTTPException(status_code=500, detail=f"Error en base de datos: {err}")
    finally:
        cursor.close()
        conexion.close()


@router.post("/verify")
def verify_totp(datos: DatosValidacionTOTP):
    """
    Validates a 6-digit TOTP verification token generated by an authenticator app.
    """
    conexion = obtener_conexion()
    if not conexion:
        raise HTTPException(status_code=500, detail="Error de conexión a la base de datos.")

    ensure_totp_column_exists(conexion)
    cursor = conexion.cursor()

    try:
        cursor.execute("SELECT totp_secret FROM usuarios WHERE id_usuario = %s", (datos.id_usuario,))
        resultado = cursor.fetchone()

        if not resultado or not resultado[0]:
            raise HTTPException(status_code=400, detail="El usuario no ha configurado 2FA (TOTP).")

        totp_secret = resultado[0]
        totp = pyotp.TOTP(totp_secret)

        if not totp.verify(datos.totp_code.strip()):
            raise HTTPException(status_code=401, detail="Código de autenticación 2FA incorrecto o expirado.")

        sql_log = "INSERT INTO logs_auditoria (evento, id_usuario) VALUES (%s, %s)"
        cursor.execute(sql_log, ("Validación 2FA (TOTP) exitosa", datos.id_usuario))
        conexion.commit()

        return {"status": "Éxito", "mensaje": "Autenticación 2FA (TOTP) verificada correctamente."}

    except mysql.connector.Error as err:
        raise HTTPException(status_code=500, detail=f"Error en base de datos: {err}")
    finally:
        cursor.close()
        conexion.close()
